// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyCPrbS-OPr8sG2gPNFoUCpDWpF1H6GMqjQ',
//     appId: '1:885059926299:web:7c75db3cec2b5529057bbe',
//     messagingSenderId: '885059926299',
//     projectId: 'skilly-721b0',
//     authDomain: 'skilly-721b0.firebaseapp.com',
//     storageBucket: 'skilly-721b0.firebasestorage.app',
//     measurementId: 'G-3MDVX41SDB',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAezlRs-1idNo5SuEWxkmMVfvqo5yRI_CM',
//     appId: '1:885059926299:android:aa79b6bfbf75c1d4057bbe',
//     messagingSenderId: '885059926299',
//     projectId: 'skilly-721b0',
//     storageBucket: 'skilly-721b0.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDzOJQdUfXNj5T_923EKCfWhCLGPtaHgHo',
//     appId: '1:885059926299:ios:9a71cd52bb56fbd8057bbe',
//     messagingSenderId: '885059926299',
//     projectId: 'skilly-721b0',
//     storageBucket: 'skilly-721b0.firebasestorage.app',
//     iosBundleId: 'com.example.gradProject',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyDzOJQdUfXNj5T_923EKCfWhCLGPtaHgHo',
//     appId: '1:885059926299:ios:9a71cd52bb56fbd8057bbe',
//     messagingSenderId: '885059926299',
//     projectId: 'skilly-721b0',
//     storageBucket: 'skilly-721b0.firebasestorage.app',
//     iosBundleId: 'com.example.gradProject',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyCPrbS-OPr8sG2gPNFoUCpDWpF1H6GMqjQ',
//     appId: '1:885059926299:web:a9ffeb8570ab2d9e057bbe',
//     messagingSenderId: '885059926299',
//     projectId: 'skilly-721b0',
//     authDomain: 'skilly-721b0.firebaseapp.com',
//     storageBucket: 'skilly-721b0.firebasestorage.app',
//     measurementId: 'G-YGF706NGNB',
//   );
// }