// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLDI_lsCDbrRkt-y1TxqysWf00Tv19F-I',
    appId: '1:418727768222:web:188d6de17045a3f6df0b8f',
    messagingSenderId: '418727768222',
    projectId: 'skilly-58194',
    authDomain: 'skilly-58194.firebaseapp.com',
    storageBucket: 'skilly-58194.firebasestorage.app',
    measurementId: 'G-HCWQ0B59HS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcswNsD9nY85Cm76Fl7i7i9OQFwwa2a6U',
    appId: '1:418727768222:android:aa611a0a4df1531cdf0b8f',
    messagingSenderId: '418727768222',
    projectId: 'skilly-58194',
    storageBucket: 'skilly-58194.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxVpVgCPOHWMB6NK2LPdj0l0eyXHuaSjE',
    appId: '1:418727768222:ios:cb245c7ef6e4d8afdf0b8f',
    messagingSenderId: '418727768222',
    projectId: 'skilly-58194',
    storageBucket: 'skilly-58194.firebasestorage.app',
    iosBundleId: 'com.example.gradProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxVpVgCPOHWMB6NK2LPdj0l0eyXHuaSjE',
    appId: '1:418727768222:ios:cb245c7ef6e4d8afdf0b8f',
    messagingSenderId: '418727768222',
    projectId: 'skilly-58194',
    storageBucket: 'skilly-58194.firebasestorage.app',
    iosBundleId: 'com.example.gradProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLDI_lsCDbrRkt-y1TxqysWf00Tv19F-I',
    appId: '1:418727768222:web:df56fff69fd3c09cdf0b8f',
    messagingSenderId: '418727768222',
    projectId: 'skilly-58194',
    authDomain: 'skilly-58194.firebaseapp.com',
    storageBucket: 'skilly-58194.firebasestorage.app',
    measurementId: 'G-F03EFTJCZV',
  );
}
